title: PFCP Showcase 
views:
  - type: sections
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Full Example
            heading_style: title
            badges: []
          - type: custom:power-flow-card-plus
            entities:
              battery:
                entity: input_number.battery_power_combined
                state_of_charge: input_number.battery_soc
              grid:
                entity: input_number.grid_power_combined
              solar:
                entity: input_number.solar_power
              fossil_fuel_percentage:
                entity: input_number.fossil_fuel_percentage
            clickable_entities: true
            display_zero_lines: true
            use_new_flow_rate_model: true
            w_decimals: 0
            kw_decimals: 1
            min_flow_rate: 0.75
            max_flow_rate: 6
            max_expected_power: 2000
            min_expected_power: 0.01
            watt_threshold: 1000
            transparency_zero_lines: 0
            sort_individual_devices: false
      - type: grid
        cards:
          - type: heading
            heading: Grid Only
            heading_style: title
            icon: mdi:transmission-tower
          - type: custom:power-flow-card-plus
            entities:
              grid:
                entity: input_number.grid_power_combined
            clickable_entities: true
            display_zero_lines: true
            use_new_flow_rate_model: true
            w_decimals: 0
            kw_decimals: 1
            min_flow_rate: 0.75
            max_flow_rate: 6
            max_expected_power: 2000
            min_expected_power: 0.01
            watt_threshold: 1000
            transparency_zero_lines: 0
            sort_individual_devices: false
          - type: heading
            icon: mdi:generator-portable
            heading: Power Outage
            heading_style: subtitle
          - type: tile
            entity: input_boolean.power_outage_state
            vertical: false
            features_position: inline
            features:
              - type: toggle
          - type: custom:power-flow-card-plus
            entities:
              grid:
                entity: input_number.grid_power_combined
                power_outage:
                  entity: input_boolean.power_outage_state
                  entity_generator: input_number.generator_power
                  state_alert: 'on'
                  label_alert: Outage
            clickable_entities: true
            display_zero_lines: true
            use_new_flow_rate_model: true
            w_decimals: 0
            kw_decimals: 1
            min_flow_rate: 0.75
            max_flow_rate: 6
            max_expected_power: 2000
            min_expected_power: 0.01
            watt_threshold: 1000
            transparency_zero_lines: 0
            sort_individual_devices: false
      - type: grid
        cards:
          - type: heading
            heading: Solar
            heading_style: title
            icon: mdi:solar-power
          - type: custom:power-flow-card-plus
            entities:
              grid:
                entity: input_number.grid_power_combined
              solar:
                entity: input_number.solar_power
            clickable_entities: true
            display_zero_lines: true
            use_new_flow_rate_model: true
            w_decimals: 0
            kw_decimals: 1
            min_flow_rate: 0.75
            max_flow_rate: 6
            max_expected_power: 2000
            min_expected_power: 0.01
            watt_threshold: 1000
            transparency_zero_lines: 0
            sort_individual_devices: false
          - type: heading
            icon: mdi:transmission-tower-export
            heading: Grid Export
            heading_style: subtitle
          - type: custom:power-flow-card-plus
            entities:
              grid:
                entity:
                  consumption: input_number.grid_power_import
                  production: input_number.grid_power_export
              solar:
                entity: input_number.solar_power
            clickable_entities: true
            display_zero_lines: true
            use_new_flow_rate_model: true
            w_decimals: 0
            kw_decimals: 1
            min_flow_rate: 0.75
            max_flow_rate: 6
            max_expected_power: 2000
            min_expected_power: 0.01
            watt_threshold: 1000
            transparency_zero_lines: 0
            sort_individual_devices: false
      - type: grid
        cards:
          - type: heading
            heading: Battery
            heading_style: title
            icon: mdi:home-battery-outline
          - type: heading
            heading: Separate entities
            heading_style: subtitle
            icon: ''
          - type: custom:power-flow-card-plus
            entities:
              grid:
                entity: input_number.grid_power_combined
              solar:
                entity: input_number.solar_power
              battery:
                entity:
                  consumption: input_number.battery_power_import
                  production: input_number.battery_power_export
            clickable_entities: true
            display_zero_lines: true
            use_new_flow_rate_model: true
            w_decimals: 0
            kw_decimals: 1
            min_flow_rate: 0.75
            max_flow_rate: 6
            max_expected_power: 2000
            min_expected_power: 0.01
            watt_threshold: 1000
            transparency_zero_lines: 0
            sort_individual_devices: false
          - type: heading
            icon: ''
            heading: With SoC
            heading_style: subtitle
          - type: custom:power-flow-card-plus
            entities:
              grid:
                entity: input_number.grid_power_combined
              solar:
                entity: input_number.solar_power
              battery:
                entity:
                  consumption: input_number.battery_power_import
                  production: input_number.battery_power_export
                state_of_charge: input_number.battery_soc
                show_state_of_charge: true
            clickable_entities: true
            display_zero_lines: true
            use_new_flow_rate_model: true
            w_decimals: 0
            kw_decimals: 1
            min_flow_rate: 0.75
            max_flow_rate: 6
            max_expected_power: 2000
            min_expected_power: 0.01
            watt_threshold: 1000
            transparency_zero_lines: 0
            sort_individual_devices: false
      - type: grid
        cards:
          - type: heading
            heading: Individual Devices
            heading_style: title
            icon: mdi:devices
          - type: heading
            heading: 2 Individuals
            heading_style: subtitle
            icon: ''
          - type: custom:power-flow-card-plus
            entities:
              grid: &ref_0
                entity: input_number.grid_power_combined
              solar: &ref_1
                entity: input_number.solar_power
              battery:
                entity: &ref_2
                  consumption: input_number.battery_power_import
                  production: input_number.battery_power_export
                state_of_charge: input_number.battery_soc
              individual:
                - &ref_3
                  entity: input_number.ev_power
                  name: Car
                  icon: mdi:car-electric
                  show_direction: true
                - &ref_4
                  entity: input_number.washing_machine_power
                  name: Washing
                  icon: mdi:washing-machine
            clickable_entities: true
            display_zero_lines: true
            use_new_flow_rate_model: true
            w_decimals: 0
            kw_decimals: 1
            min_flow_rate: 0.75
            max_flow_rate: 6
            max_expected_power: 2000
            min_expected_power: 0.01
            watt_threshold: 1000
            transparency_zero_lines: 0
            sort_individual_devices: false
          - type: heading
            icon: ''
            heading: 4 Individuals
            heading_style: subtitle
          - type: custom:power-flow-card-plus
            entities:
              grid: *ref_0
              solar: *ref_1
              battery:
                entity: *ref_2
                state_of_charge: input_number.battery_soc
              individual:
                - *ref_3
                - *ref_4
                - entity: input_number.dishwasher_power
                  name: DIshwasher
                  icon: mdi:dishwasher
                - entity: input_number.dryer_power
                  name: Dryer
                  icon: mdi:tumble-dryer
            clickable_entities: true
            display_zero_lines: true
            use_new_flow_rate_model: true
            w_decimals: 0
            kw_decimals: 1
            min_flow_rate: 0.75
            max_flow_rate: 6
            max_expected_power: 2000
            min_expected_power: 0.01
            watt_threshold: 1000
            transparency_zero_lines: 0
            sort_individual_devices: false
    max_columns: 2
    cards: []
    dense_section_placement: true
